Repository pbl-2018-hillclimb/burning-pro-server, pull requests merged in 2018-10, with the labels that each got.

#27 Add types to insert new row to DB
  burning-pro-server/src/models/mod.rs
  burning-pro-server/src/models/update.rs
Labels: enhancement

#29 Add message types to query row of a table
  burning-pro-server/src/db/admin.rs
  burning-pro-server/src/db/get_rows.rs
  burning-pro-server/src/db/get_tags_for_phrase.rs
  burning-pro-server/src/db/mod.rs
Labels: enhancement

#30 Add types for upsert query
  burning-pro-server/src/db/mod.rs
  burning-pro-server/src/db/upsert_entry.rs
Labels: difficulty/1

#32 Make rows queryable by more types of IDs
  burning-pro-server/src/db/get_rows.rs
Labels: difficulty/1, enhancement

#33 Implement upsert logic for existing query types
  burning-pro-server/src/db/upsert_entry.rs
  burning-pro-server/src/models/update.rs
Labels: difficulty/5, enhancement

#36 Silence diesel warnings which would be fixed in diesel-1.4
  burning-pro-server/src/db/upsert_entry.rs
  burning-pro-server/src/models/mod.rs
  burning-pro-server/src/models/update.rs
  burning-pro-server/src/schema.rs
Labels: difficulty/1, enhancement, task, waiting for review

#39 Tiny refactoring on current `develop` branch
  burning-pro-server/src/db/admin.rs
  burning-pro-server/src/db/upsert_entry.rs
Labels: difficulty/0, enhancement, task

#21 DBへの登録用フォームの作成
  burning-pro-server/Cargo.toml
  burning-pro-server/migrations/2018-07-03-082532_seed_good_phrases/up.sql
  burning-pro-server/src/admin/form.rs
  burning-pro-server/src/admin/mod.rs
  burning-pro-server/src/admin/person.rs
  burning-pro-server/src/admin/phrase.rs
  burning-pro-server/src/admin/tag.rs
  burning-pro-server/src/app/state.rs
  burning-pro-server/src/bin/burning-pro-server.rs
  burning-pro-server/src/lib.rs
  burning-pro-server/templates/register/index.html
  burning-pro-server/templates/register/person/index.html
  burning-pro-server/templates/register/person/new.html
  burning-pro-server/templates/register/person/post.html
  burning-pro-server/templates/register/person/update.html
  burning-pro-server/templates/register/phrase/index.html
  burning-pro-server/templates/register/phrase/new.html
  burning-pro-server/templates/register/phrase/post.html
  burning-pro-server/templates/register/phrase/update.html
  burning-pro-server/templates/register/tag/index.html
  burning-pro-server/templates/register/tag/new.html
  burning-pro-server/templates/register/tag/post.html
  burning-pro-server/templates/register/tag/update.html
Labels: difficutly/8, enhancement, task

#40 Remove CI build and test for nightly rustc
  .travis.yml
Labels: difficulty/0, enhancement, task, waiting for review

#41 Make DB migration sane
  burning-pro-server/migrations/2018-06-25-073950_create_good_phrases/up.sql
  burning-pro-server/migrations/2018-07-03-082532_seed_good_phrases/down.sql
  burning-pro-server/migrations/2018-07-03-082532_seed_good_phrases/up.sql
  burning-pro-server/src/admin/form.rs
  burning-pro-server/src/db/upsert_entry.rs
  burning-pro-server/src/good_phrase/response.rs
  burning-pro-server/src/lib.rs
  burning-pro-server/src/models/mod.rs
  burning-pro-server/src/models/update.rs
  burning-pro-server/src/schema.rs
Labels: difficulty/2, enhancement, task, waiting for review

#42 Refactor html templates and related logics
  .editorconfig
  burning-pro-server/src/admin/mod.rs
  burning-pro-server/src/admin/person.rs
  burning-pro-server/src/admin/phrase.rs
  burning-pro-server/src/admin/tag.rs
  burning-pro-server/src/bin/burning-pro-server.rs
  burning-pro-server/src/db/upsert_entry.rs
  burning-pro-server/templates/register/index.html
  burning-pro-server/templates/register/list.html
  burning-pro-server/templates/register/person/index.html
  burning-pro-server/templates/register/person/new.html
  burning-pro-server/templates/register/person/post.html
  burning-pro-server/templates/register/person/update.html
  burning-pro-server/templates/register/phrase/index.html
  burning-pro-server/templates/register/phrase/new.html
  burning-pro-server/templates/register/phrase/post.html
  burning-pro-server/templates/register/phrase/update.html
  burning-pro-server/templates/register/tag/index.html
  burning-pro-server/templates/register/tag/new.html
  burning-pro-server/templates/register/tag/post.html
  burning-pro-server/templates/register/tag/update.html
Labels: difficulty/2, enhancement, task, waiting for review
