Repository pbl-2018-hillclimb/burning-pro-server, pull requests merged in 2018-11, with the labels that each got.

#43 Require Basic auth for admin web UI
  Dockerfile
  burning-pro-server/.env
  burning-pro-server/.gitignore
  burning-pro-server/Cargo.toml
  burning-pro-server/src/app/auth.rs
  burning-pro-server/src/app/mod.rs
  burning-pro-server/src/app/state.rs
  burning-pro-server/src/bin/burning-pro-server.rs
  burning-pro-server/template.env
  deploy.sh
Labels: difficulty/2, enhancement, task, waiting for review

#46 Make listen address and port configurable
  burning-pro-server/src/bin/burning-pro-server.rs
  burning-pro-server/template.env
Labels: difficulty/1, enhancement, task, waiting for review

#50 Feature/db register from app revenge
  burning-pro-server/migrations/2018-11-02-072619_create_good_phrase_requests/down.sql
  burning-pro-server/migrations/2018-11-02-072619_create_good_phrase_requests/up.sql
  burning-pro-server/src/admin/form.rs
  burning-pro-server/src/admin/mod.rs
  burning-pro-server/src/admin/phrase_request.rs
  burning-pro-server/src/bin/burning-pro-server.rs
  burning-pro-server/src/db/upsert_entry.rs
  burning-pro-server/src/models/update.rs
  burning-pro-server/src/schema.rs
Labels: enhancement, waiting for review

#51 Fix lint warnings
  burning-pro-server/src/admin/form.rs
  burning-pro-server/src/admin/phrase_request.rs
  burning-pro-server/src/db/upsert_entry.rs
Labels: difficulty/0, task, waiting for review

#55 Update dependencies
  Cargo.lock
Labels: difficulty/0, enhancement, task, waiting for review

#56 Resolve lint warnings
  burning-pro-server/src/admin/phrase_request.rs
  burning-pro-server/src/db/get_rows.rs
Labels: difficulty/0, enhancement, task, waiting for review
