Repository pbl-2018-hillclimb/burning-pro-server, pull requests merged in 2018-07, with the labels that each got.

#6 Returns sample (dummy) JSON response for `/imprudences/` path
  burning-pro-server/Cargo.toml
  burning-pro-server/src/imprudence/mod.rs
  burning-pro-server/src/imprudence/response.rs
  burning-pro-server/src/main.rs
Labels: enhancement, waiting for review

#10 Load imprudences and related data from DB
  .editorconfig
  burning-pro-server/.env
  burning-pro-server/.gitignore
  burning-pro-server/Cargo.toml
  burning-pro-server/diesel.toml
  burning-pro-server/migrations/.gitkeep
  burning-pro-server/migrations/2018-06-25-073950_create_imprudences/down.sql
  burning-pro-server/migrations/2018-06-25-073950_create_imprudences/up.sql
  burning-pro-server/migrations/2018-07-03-082532_seed_imprudences/down.sql
  burning-pro-server/migrations/2018-07-03-082532_seed_imprudences/up.sql
  burning-pro-server/src/db/mod.rs
  burning-pro-server/src/imprudence/mod.rs
  burning-pro-server/src/imprudence/response.rs
  burning-pro-server/src/main.rs
  burning-pro-server/src/models/mod.rs
  burning-pro-server/src/schema.rs
Labels: enhancement, waiting for review

#12 Allow dotenv file to be nonexistent
  burning-pro-server/Cargo.toml
  burning-pro-server/src/main.rs
Labels: bug, waiting for review

#11 Feature/create dockerfile
  Dockerfile
Labels: enhancement, waiting for review

#13 Refactor and add a basic manual
  README.md
  burning-pro-server/.gitignore
  burning-pro-server/.rustfmt.toml
  burning-pro-server/Cargo.lock
  burning-pro-server/src/app/mod.rs
  burning-pro-server/src/app/state.rs
  burning-pro-server/src/bin/burning-pro-server.rs
  burning-pro-server/src/db/get_imprudences.rs
  burning-pro-server/src/db/mod.rs
  burning-pro-server/src/imprudence/mod.rs
  burning-pro-server/src/imprudence/response.rs
  burning-pro-server/src/lib.rs
  burning-pro-server/src/models/mod.rs
  docs/database.md
  docs/server-dev.md
Labels: waiting for review

#15 Add deploy script
  deploy.sh
Labels: waiting for review
